version: '3.7'

services:
  gitlab:
    image: 'gitlab/gitlab-ec:latest'
    container_name: gitlab
    restart: always
    hostname: 'my-gitlab'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://4.217.179.87:8081'
    ports:
      - '8081:80'
      - '443:443'
      - '22:22'
    volumes:
      - '/var/gitlab/config:/etc/gitlab'
      - '/var/gitlab/logs:/var/log/gitlab'
      - '/var/gitlab/data:/var/opt/gitlab'

  jenkins:
    image: 'jenkins/jenkins:lts'
    container_name: jenkins
    restart: always
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - '/var/jenkins_home:/var/jenkins_home'